name: Continious Integration
env:
  DOCKER_IMAGE: wyrihaximusnet/telegraf
  TAG_VERSION: 1.12
on: [push]
jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint Dockerfile
        uses: docker://hadolint/hadolint:latest-debian
        with:
          entrypoint: hadolint
          args: Dockerfile
  build-docker-image:
    needs:
      - lint-dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker image build -t "${DOCKER_IMAGE}:${TAG_VERSION}" . --no-cache --build-arg VERSION=$TAG_VERSION
      - run: mkdir ./docker-image
      - run: docker save "${DOCKER_IMAGE}:${TAG_VERSION}" -o ./docker-image/docker_image.tar
      - uses: actions/upload-artifact@master
        with:
          name: docker-image
          path: ./docker-image
  scan-vulnerability:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install clair-scanner
        run: |
          sudo curl -L https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64 -o /usr/local/bin/clair-scanner
          sudo chmod +x /usr/local/bin/clair-scanner
      - uses: actions/download-artifact@master
        with:
          name: docker-image
          path: ./docker-image
      - run: docker load --input ./docker-image/docker_image.tar
      - run: rm -Rf ./docker-image/
      - run: mkdir -p "./clair/${DOCKER_IMAGE}"
      - run: docker-compose -f .docker/security/docker-compose.yml -p clair-ci up -d
#      - run: RETRIES=0 && while ! wget -T 10 -q -O /dev/null http://localhost:6060/v1/namespaces ; do sleep 1 ; echo -n "." ; if [ $${RETRIES} -eq 10 ] ; then echo " Timeout, aborting." ; exit 1 ; fi ; RETRIES=$$(($${RETRIES}+1)) ; done
      - run: sleep 10
      - run: echo -e "${DOCKER_IMAGE}:${TAG_VERSION}" | xargs -I % sh -c 'clair-scanner --ip 172.17.0.1 -r "./clair/%.json" -l ./clair/clair.log % || (echo "% is vulnerable" && exit 1)'
      - run: docker-compose -f .docker/security/docker-compose.yml -p clair-ci down
